create table "dev_post_document" (
    id serial,
    category varchar(200) not null,
    list_tag varchar(100),
    list_id varchar(100),
    list_class varchar(100),
    title_tag varchar(100),
    title_id varchar(100),
    title_class varchar(100),
    description_tag varchar(100),
    description_id varchar(100),
    description_class varchar(100),
    writer_tag varchar(100),
    writer_id varchar(100),
    writer_class varchar(100),
    url_tag varchar(100),
    url_id varchar(100),
    url_class varchar(100),
    upload_date_tag varchar(100),
    upload_date_id varchar(100),
    upload_date_class varchar(100),
    thumbnail_tag varchar(100),
    thumbnail_id varchar(100),
    thumbnail_class varchar(100),
    paging varchar(200),
    tags_tag varchar(100),
    tags_id varchar(100),
    tags_class varchar(100),
    create_at timestamp with time zone not null default now(),
    update_at timestamp with time zone not null default now(),
    constraint pk_dev_post_document_id primary key (id)
)