create table "member" (
  id serial,
  status varchar(50) not null,
  email varchar(300) not null,
  username varchar(200) not null,
  password varchar(300) not null,
  authority varchar[] not null default '{}',
  path_base varchar(500),
  image_path varchar[],
  description text,
  github varchar(400),
  facebook varchar(400),
  twiter varchar(400),
  instagram varchar(400),
  linked_in varchar(400),
  create_at timestamp with time zone not null default now(),
  update_at timestamp with time zone not null default now(),
  constraint pk_member_id primary key (id),
  constraint uk_member_email unique (email)
)